// api/flutterwave/webhook.js  ->  deploys as POST /api/flutterwave/webhook on Vercel
//
// Flow:
// 1. Check verif-hash header against FLW_SECRET_HASH (proves the sender knows our secret).
// 2. Re-fetch the transaction from Flutterwave's Verify API (never trust the payload's amount/status).
// 3. Confirm amount, currency and the vendor/plan we expected (via the tx_ref we generated at checkout).
// 4. Idempotency: skip if we've already processed this transaction id.
// 5. Activate Premium in Firestore + send the payment-success email.
//
// Requires env vars: FLW_SECRET_KEY, FLW_SECRET_HASH
// Requires FLW_PLANS to match what you charge, e.g. { "NGN": 2000, "USD": 2.5 }

const crypto = require("crypto");
const { db, admin } = require("../../lib/firebaseAdmin");
const { sendPaymentSuccessEmail } = require("../../lib/email");
const config = require("../../lib/config");

const EXPECTED_PLAN_AMOUNTS = {
  NGN: config.PREMIUM_NGN_PRICE,
  USD: config.PREMIUM_USD_PRICE,
};

module.exports = async function handler(req, res) {
  if (req.method !== "POST") {
    return res.status(405).send("Method not allowed");
  }

  // --- 1. Verify the shared-secret header ---
  const signature = req.headers["verif-hash"];
  const expected = process.env.FLW_SECRET_HASH;

  if (!signature || !expected || !timingSafeEqual(signature, expected)) {
    return res.status(401).send("Invalid signature");
  }

  // Acknowledge fast, do the real work after — Flutterwave retries on non-200/slow responses.
  res.status(200).send("OK");

  try {
    const event = req.body;
    const txId = event?.data?.id;

    if (!txId) {
      console.error("Webhook missing transaction id", event);
      return;
    }

    // --- 2. Re-verify the transaction server-side (never trust the webhook body alone) ---
    const verifyRes = await fetch(
      `https://api.flutterwave.com/v3/transactions/${txId}/verify`,
      {
        headers: { Authorization: `Bearer ${process.env.FLW_SECRET_KEY}` },
      }
    );
    const verifyData = await verifyRes.json();
    const tx = verifyData?.data;

    if (!tx || verifyData.status !== "success" || tx.status !== "successful") {
      console.log(`Transaction ${txId} not successful, ignoring`, tx?.status);
      return;
    }

    // --- 3. Confirm this matches something we actually created at checkout ---
    // tx.tx_ref should have been generated by us as e.g. "wyte_<vendorId>_<plan>_<random>"
    const parsed = parseTxRef(tx.tx_ref);
    if (!parsed) {
      console.error("Unrecognized tx_ref format, refusing to activate:", tx.tx_ref);
      return;
    }
    const { vendorId } = parsed;

    const expectedAmount = EXPECTED_PLAN_AMOUNTS[tx.currency];
    if (expectedAmount === undefined || Number(tx.amount) < expectedAmount) {
      console.error("Amount/currency mismatch — not activating", tx.amount, tx.currency);
      return;
    }

    // --- 4. Idempotency: have we processed this transaction id before? ---
    const eventRef = db.collection("webhookEvents").doc(String(txId));
    const alreadyProcessed = await db.runTransaction(async (t) => {
      const snap = await t.get(eventRef);
      if (snap.exists) return true;
      t.set(eventRef, {
        txId,
        vendorId,
        processedAt: admin.firestore.FieldValue.serverTimestamp(),
      });
      return false;
    });

    if (alreadyProcessed) {
      console.log(`Transaction ${txId} already processed, skipping`);
      return;
    }

    // --- 5. Activate Premium ---
    const startDate = new Date();
    const expiryDate = new Date(startDate);
    expiryDate.setMonth(expiryDate.getMonth() + 1);

    const vendorRef = db.collection("vendors").doc(vendorId);
    await vendorRef.set(
      {
        plan: "premium",
        subscriptionStatus: "active",
        subscriptionStart: startDate.toISOString(),
        subscriptionExpiry: expiryDate.toISOString(),
      },
      { merge: true }
    );

    await db.collection("payments").add({
      vendorId,
      txId,
      txRef: tx.tx_ref,
      amount: tx.amount,
      currency: tx.currency,
      status: "success",
      createdAt: admin.firestore.FieldValue.serverTimestamp(),
    });

    // --- Send the payment success email ---
    const vendorSnap = await vendorRef.get();
    const vendor = vendorSnap.data();

    if (vendor?.email) {
      await sendPaymentSuccessEmail({
        to: vendor.email,
        businessName: vendor.businessName,
        plan: "Premium",
        amount: tx.amount,
        currencyCode: tx.currency,
        startDate: startDate.toDateString(),
        expiryDate: expiryDate.toDateString(),
        txRef: tx.tx_ref,
      });
    }
  } catch (err) {
    console.error("Error processing Flutterwave webhook:", err);
  }
};

function timingSafeEqual(a, b) {
  const bufA = Buffer.from(String(a));
  const bufB = Buffer.from(String(b));
  if (bufA.length !== bufB.length) return false;
  return crypto.timingSafeEqual(bufA, bufB);
}

// Expects tx_ref generated at checkout time like: wyte_<vendorId>_<plan>_<random>
function parseTxRef(txRef) {
  if (!txRef || typeof txRef !== "string") return null;
  const parts = txRef.split("_");
  if (parts[0] !== "wyte" || parts.length < 3) return null;
  return { vendorId: parts[1], plan: parts[2] };
}
